language: php
php:
  - 7.2
before_script: 
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get -qq update
  - sudo apt-get install -y php7.0-fpm
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction

deploy:
  provider: heroku
  api_key:
    secure: "6b1b01c1-83e5-4165-9b4d-3595be720fcf"
  app:
    master: 'redator-api'