sudo: required

language: php
php:
  - 7.2

services:
  - docker

before_install:
  - docker-compose up -d

before_script: 
  - composer self-update
  - composer install --no-interaction

script:
  - docker exec -it redator vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: "6b1b01c1-83e5-4165-9b4d-3595be720fcf"
  app:
    master: 'redator-api'