sudo: required

language: php
php:
  - 7.2

services:
  - docker

before_install:
  - docker-compose up -d

before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - docker exec -it redator vendor/bin/phpunit

deploy:
  - provider: script
    script: bash docker/deploy.sh production
    on:
      branch: master
  - provider: script
    script: bash docker/deploy.sh development
    on:
      all_branches: true