app:
  name: 'Redator'
  debug: true
  path: 'src/App/'
  containers:
    - App\Containers\DatabaseContainer
    - App\Containers\RepositoriesContainer
    - App\Containers\DumpsContainer
    - App\Containers\ServicesContainer
    - App\Containers\ControllersContainer
    - App\Containers\DumpsFactoriesContainer
    - App\Containers\EntityContainer
    - App\Containers\QuerysContainer
    - App\Containers\CommandsContainer
    - App\Containers\FactoriesContainer
  routes: 'src/App/routes.php'
  orm: 'doctrine'
