app:
  name: 'Redator'
  debug: true
  path: 'src/App/'
  containers:
    - App\Containers\DatabaseContainer
    - App\Containers\RepositoriesContainer
  routes: 'src/App/routes.php'
  orm: 'doctrine'