app:
  name: 'Redator'
  debug: true
  path: 'src/App/'
  containers:
    - App\Containers\DatabaseContainer
    - App\Containers\RepositoriesContainer
    - App\Containers\DumpsContainer
    - App\Containers\ServicesContainer
    - App\Containers\ControllersContainer
    - App\Containers\DumpsFactoriesContainer
    - App\Containers\FiltersContainer
    - App\Containers\EntityContainer
  routes: 'src/App/routes.php'
  orm: 'doctrine'
  templates_path: 'public/templates'
  worker_dir: 'worker.php'